name: wingx_shop
description: Wing Shop Project.
publish_to: 'zivhsiao'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  dio: ^5.3.2
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_html: ^3.0.0-beta.2
  flutter_launcher_icons: ^0.13.1
  font_awesome_flutter: ^10.5.0
  http: ^1.1.0
  lottie: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/splash_screen.json

flutter_icons:
  android: "launcher_icon" 
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon.png"